apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sso-saml
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-sso-saml
